services:
  - type: web
    name: hr-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_HOST
        fromFullUrl: true
      - key: PYTHON_VERSION
        value: 3.10.0
